# This workflow will install Python dependencies, run tests, and report the coverage with a variety of Python versions and OSs.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 0 * * *' # every midnight

jobs:
  test:
    name: Test (${{ matrix.os }}, python version ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"] # list of Python versions to test
        exclude:
          - os: windows-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "3.9"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install rdkit
          conda install pytorch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 cpuonly -c pytorch
          conda install pyg==2.2.0 -c pyg
          pip install -e .[dev]
        shell: bash -l {0}
      - name: Run tests
        id: run_tests
        run: |
          pytest --nbmake --nbmake-timeout=3000 --cov=kale
        shell: bash -l {0}
      - name: Determine coverage
        run: |
          coverage xml
        shell: bash -l {0}
      - name: Report coverage
        uses: codecov/codecov-action@v1
